import {
  EXAMPLE_INVOICE_CHARGEITEM_CATEGORY,
  EXAMPLE_INVOICE_CHARGEITEM_CODE_TEXT,
  EXAMPLE_INVOICE_CHARGEITEM_IDENTIFIER,
  EXAMPLE_INVOICE_CHARGEITEM_ITEMS_PER_UNIT,
  EXAMPLE_INVOICE_CHARGEITEM_ITEMS_QUANTITY,
  EXAMPLE_INVOICE_CHARGEITEM_ITEMS_QUANTITY_NUMBER,
  EXAMPLE_INVOICE_CHARGEITEM_ITEMS_QUANTITY_UNIT,
  EXAMPLE_INVOICE_CHARGEITEM_PART_OF,
  EXAMPLE_INVOICE_CHARGEITEM_PRODUCT_CODE,
  EXAMPLE_INVOICE_CHARGEITEM_QUANTITY,
  EXAMPLE_INVOICE_CHARGEITEM_QUANTITY_NUMBER,
  EXAMPLE_INVOICE_CHARGEITEM_STATUS,
  EXAMPLE_INVOICE_CHARGEITEM_SUPPLIER_PRODUCT_CODE,
  EXAMPLE_INVOICE_CHARGEITEM_QUANTITY_UNIT,
  EXAMPLE_API_ORGANIZATION_DID,
  EXAMPLE_CONTENT_TYPE_APPLICATION_JSON,
  EXAMPLE_DOCUMENT_REFERENCE_CONTENT_TYPE_PDF,
  EXAMPLE_DOCUMENT_REFERENCE_LANGUAGE,
  EXAMPLE_LICENSE_AMOUNT,
  EXAMPLE_LICENSE_INVOICE_ID,
  EXAMPLE_LICENSE_PAYMENT_METHOD_INVOICE,
  EXAMPLE_LICENSE_PAYMENT_URL,
  EXAMPLE_LICENSE_CURRENCY,
  EXAMPLE_SUBJECT_DID,
  EXAMPLE_INVOICE_DATE,
  EXAMPLE_VAULT_PRIMARY_DATE_TIME,
} from './shared';
import {
  ChargeItemClaim,
  InvoiceClaim,
} from '../models/interoperable-claims/invoice-claims';
import { createInvoiceBundleEditor } from '../utils/invoice-bundle';

export const EXAMPLE_INVOICE_PDF_DOCUMENT = Object.freeze({
  documentId: `${EXAMPLE_LICENSE_INVOICE_ID}-pdf`,
  contentType: EXAMPLE_DOCUMENT_REFERENCE_CONTENT_TYPE_PDF,
  title: `${EXAMPLE_LICENSE_INVOICE_ID}.pdf`,
  description: 'Human-readable invoice PDF',
  language: EXAMPLE_DOCUMENT_REFERENCE_LANGUAGE,
  dataBase64: 'JVBERi0xLjQKJUZha2UgaW52b2ljZSBQREYK',
  createdAt: EXAMPLE_VAULT_PRIMARY_DATE_TIME,
} as const);

export const EXAMPLE_INVOICE_JSON_DOCUMENT = Object.freeze({
  documentId: `${EXAMPLE_LICENSE_INVOICE_ID}-json`,
  contentType: EXAMPLE_CONTENT_TYPE_APPLICATION_JSON,
  title: `${EXAMPLE_LICENSE_INVOICE_ID}.json`,
  description: 'Structured invoice JSON',
  language: EXAMPLE_DOCUMENT_REFERENCE_LANGUAGE,
  dataBase64: 'eyJpbnZvaWNlSWQiOiJpbnZvaWNlLTAwMSJ9',
  createdAt: EXAMPLE_VAULT_PRIMARY_DATE_TIME,
} as const);

export const EXAMPLE_INVOICE_BUNDLE = Object.freeze(
  createInvoiceBundleEditor()
    .setInvoiceId(EXAMPLE_LICENSE_INVOICE_ID)
    .setSubjectReference(EXAMPLE_SUBJECT_DID)
    .setIssuerReference(EXAMPLE_API_ORGANIZATION_DID)
    .setRecipientReference(EXAMPLE_SUBJECT_DID)
    .setIssuedAt(EXAMPLE_INVOICE_DATE)
    .setAmount(EXAMPLE_LICENSE_AMOUNT)
    .setCurrency(EXAMPLE_LICENSE_CURRENCY)
    .setPaymentMethod(EXAMPLE_LICENSE_PAYMENT_METHOD_INVOICE)
    .setPaymentUrl(EXAMPLE_LICENSE_PAYMENT_URL)
    .setPdfDocument(EXAMPLE_INVOICE_PDF_DOCUMENT)
    .setStructuredDocument(EXAMPLE_INVOICE_JSON_DOCUMENT)
    .buildBundle(),
);

export const EXAMPLE_INVOICE_CHARGE_ITEM_ROW_A = Object.freeze({
  identifier: EXAMPLE_INVOICE_CHARGEITEM_IDENTIFIER,
  status: EXAMPLE_INVOICE_CHARGEITEM_STATUS,
  partOf: EXAMPLE_INVOICE_CHARGEITEM_PART_OF,
  code: EXAMPLE_INVOICE_CHARGEITEM_PRODUCT_CODE,
  codeText: EXAMPLE_INVOICE_CHARGEITEM_CODE_TEXT,
  category: EXAMPLE_INVOICE_CHARGEITEM_CATEGORY,
  supplierProductCode: EXAMPLE_INVOICE_CHARGEITEM_SUPPLIER_PRODUCT_CODE,
  quantity: EXAMPLE_INVOICE_CHARGEITEM_QUANTITY,
  quantityNumber: EXAMPLE_INVOICE_CHARGEITEM_QUANTITY_NUMBER,
  quantityUnit: EXAMPLE_INVOICE_CHARGEITEM_QUANTITY_UNIT,
  itemsPerUnit: EXAMPLE_INVOICE_CHARGEITEM_ITEMS_PER_UNIT,
  itemsQuantity: EXAMPLE_INVOICE_CHARGEITEM_ITEMS_QUANTITY,
  itemsQuantityNumber: EXAMPLE_INVOICE_CHARGEITEM_ITEMS_QUANTITY_NUMBER,
  itemsQuantityUnit: EXAMPLE_INVOICE_CHARGEITEM_ITEMS_QUANTITY_UNIT,
} as const);

export const EXAMPLE_INVOICE_FHIR_CLAIMS = Object.freeze(
  createInvoiceBundleEditor()
    .setInvoiceId(EXAMPLE_LICENSE_INVOICE_ID)
    .setSubjectReference(EXAMPLE_SUBJECT_DID)
    .setIssuerReference(EXAMPLE_API_ORGANIZATION_DID)
    .setRecipientReference(EXAMPLE_SUBJECT_DID)
    .setIssuedAt(EXAMPLE_INVOICE_DATE)
    .setAmount(EXAMPLE_LICENSE_AMOUNT)
    .setCurrency(EXAMPLE_LICENSE_CURRENCY)
    .setPaymentMethod(EXAMPLE_LICENSE_PAYMENT_METHOD_INVOICE)
    .setPaymentUrl(EXAMPLE_LICENSE_PAYMENT_URL)
    .buildInvoiceClaims(),
);

export const EXAMPLE_INVOICE_CHARGEITEM_FHIR_CLAIMS_ROWS = Object.freeze(
  createInvoiceBundleEditor()
    .setInvoiceId(EXAMPLE_LICENSE_INVOICE_ID)
    .setSubjectReference(EXAMPLE_SUBJECT_DID)
    .setIssuerReference(EXAMPLE_API_ORGANIZATION_DID)
    .setRecipientReference(EXAMPLE_SUBJECT_DID)
    .setIssuedAt(EXAMPLE_INVOICE_DATE)
    .setAmount(EXAMPLE_LICENSE_AMOUNT)
    .setCurrency(EXAMPLE_LICENSE_CURRENCY)
    .setPaymentMethod(EXAMPLE_LICENSE_PAYMENT_METHOD_INVOICE)
    .setPaymentUrl(EXAMPLE_LICENSE_PAYMENT_URL)
    .addChargeItem(EXAMPLE_INVOICE_CHARGE_ITEM_ROW_A)
    .buildChargeItemClaimRows(),
);
