// src/models/device-license.ts
// Copyright 2025 Antifraud Services Inc. under the Apache License, Version 2.0.

import type { DeviceAppType, DeviceUserClass } from '../constants/device';

/**
 * A fingerprint of a specific device, used for binding a license to it.
 */
export interface DeviceInfo {
  /**
   * A stable, unique identifier for the specific app installation, generated by the client.
   * This is the primary key for device binding.
   */
  clientInstanceId: string;

  /** The operating system of the device (e.g., "iOS", "Android", "Windows"). */
  os?: string;

  /** The specific OS version. */
  osVersion?: string;

  /** The manufacturer of the device (e.g., "Apple", "Samsung"). */
  manufacturer?: string;
  
  /** The model of the device (e.g., "iPhone14,6"). */
  model?: string;
}

/** One concrete DCR client/application installation bound to a licensed seat. */
export interface DeviceBinding {
  /** Authorization-server assigned DCR client identifier. */
  clientId: string;

  /** Stable application installation fingerprint supplied by the client. */
  clientInstanceId: string;

  /** Current relationship between this installation and the seat. */
  status: 'active' | 'revoked';

  /** Device/application metadata captured during DCR. */
  deviceInfo: DeviceInfo;

  activatedAt: number;
  revokedAt?: number;
}

/**
 * A set of rules that a device must match to be eligible to activate a license.
 */
export interface DeviceRestrictions {
  /** A regex pattern for the allowed manufacturer(s). */
  manufacturer?: string;

  /** A regex pattern for the allowed model(s). */
  model?: string;
}

/**
 * Represents a single device activation license, enabling a user to register a specific device
 * for a tenant's service. It governs access based on user class, platform, and subscription terms.
 * Timestamps are stored as Unix epoch seconds (numeric).
 * All property names follow the camelCase convention.
 */
export interface DeviceLicense {
  /**
   * The unique identifier for this license document in the vault.
   */
  id: string;

  /**
   * The logical identifier of the tenant organization that owns this license.
   * @example "acme"
   */
  tenantId: string;

  /**
   * Organization that owns this seat pool.
   *
   * This is essential for hosted individual organizations because many
   * households can share one tenant vault. It is distinct from
   * `subjectId`, which identifies the member currently assigned to the seat.
   */
  ownerOrganizationId?: string;

  /** Subject/card DID made accessible when this member invitation is accepted. */
  authorizedSubjectDid?: string;
  
  /**
   * Identifier for the purchase order or invoice that generated this license.
   * All licenses created from the same purchase will share the same orderId.
   * @example "inv_12345"
   */
  orderId: string;

  /**
   * A secure, single-use code given to a user to activate a device.
   * This is generated when the license status becomes 'issued'.
   */
  activationCode?: string;

  /**
   * **CRITICAL:** Defines the class of user this license is intended for.
   * This allows for stratified licensing (e.g., selling "professional seats"
   * separately from "individual access").
   */
  userClass: DeviceUserClass;

  /**
   * **Specifies the functional category for an 'employee' license.**
   * This determines the set of roles the user is permitted to have.
   * This field MUST be present if userClass is 'employee'.
   * It is typically undefined for 'individual' licenses.
   * @example "medicalStaff", "firstResponder", "admin"
   */
  userCategory?: string;


  /**
   * Defines the platform this license is for.
   */
  type: DeviceAppType;

  /**
   * The current lifecycle status of the license.
   * - 'available': Fresh license, ready to be assigned to a user.
   * - 'issued': Assigned to a user and an activation code has been generated.
   * - 'active': The user has successfully used the activation code to register a device.
   * - 'inactive': Deactivated by an administrator or user, or has expired.
   */
  status: 'available' | 'issued' | 'active' | 'inactive';

  /**
   * The subscription or purchase plan associated with this license.
   * @example "premium_annual" | "standard_monthly" | "trial"
   */
  plan: string;

  /**
   * Defines the renewal period for the license.
   * '1m' for one month, '12m' for one year.
   * A null value indicates the license does not auto-renew.
   */
  renewalCycle: '1m' | '12m' | null;
  
  /**
   * If true, the license can be reactivated after being made inactive
   * (e.g., after a user clicks "Log out everywhere"). If false, an inactive
   * license cannot be used again.
   */
  reactivationEnabled: boolean;

  /**
   * "Issued At" timestamp. The time the license was assigned to a user, as a Unix epoch in seconds.
   * Set when status moves to 'issued'.
   */
  issuedAt?: number;
  
  /**
   * "Activation Time" timestamp. The time the license was successfully used to register a device,
   * as a Unix epoch in seconds. Set when status moves to 'active'.
   */
  activatedAt?: number;

  /**
   * "Expiration Time" timestamp. The time at which the license and the device's authorization
   * expire, as a Unix epoch in seconds.
   */
  exp: number;

  /**
   * The unique identifier of the user (e.g., employeeId or customerId) to whom the license is issued.
   * Populated when the status becomes 'issued'.
   */
  subjectId?: string;

  /** Verified email selected from the invited contact, when email is used. */
  issuedToEmail?: string;

  /** Verified ITU telephone selected from the invited contact, when phone is used. */
  issuedToPhone?: string;

  /** Canonical FHIR v3 or ISCO role used to choose the owning license pool. */
  issuedToRole?: string;

  /** Relationship invitation workflow that reserved this seat. */
  invitationId?: string;

  /** RelatedPerson/contact selected before the invitation was sent. */
  relatedPersonId?: string;
  
  /**
   * The unique identifier (`client_id`) of the device registered with this license.
   * Populated when the status becomes 'active'.
   */
  deviceId?: string;

  /**
   * Maximum number of simultaneously active DCR installations for this seat.
   * Defaults to two when omitted for legacy records.
   */
  maxDevices?: number;

  /** All DCR installations bound to this user/member seat. */
  deviceBindings?: DeviceBinding[];

  /**
   * Stable private contact identifier: `urn:multibase:<hash(normalized email or phone)>`.
   * The canonical ISCO-08/FHIR-v3 role is stored separately in `issuedToRole`.
   * Portal DIDs, IdP subjects, wallets and DCR clients bind to this value but do not define it.
   */
  activatedBy?: string;

  /**
   * Optional, pre-defined restrictions on which devices are allowed to activate this license.
   * Set at the time of license creation.
   */
  deviceRestrictions?: DeviceRestrictions;

  /**
   * A fingerprint of the device that successfully activated this license.
   * This is captured upon activation and is used to lock the license to that specific device.
   */
  deviceInfo?: DeviceInfo;
}
